#!/usr/bin/env zsh

function git-stats () {
    clear
    git --no-pager diff --shortstat
    git status --short
}

# Save terminal state; restore on exit
tput smcup
trap 'tput rmcup' INT TERM

# Initially
git-stats

# And again whenever a file changes
inotifywait --quiet --monitor --recursive \
    --event close_write,move,create,delete \
    --format "%f %e" @./.git . \
    | while read file; do git-stats; done
